### ISSUE TITLE
1.2.1. Umgang mit OpenData-Portalen

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#10]
Erstellung einer Kontaktübersichtsliste OpenData-Portale NRW/nördliches RLP

z.B.: "https://offenedaten-koeln.de/" -> Kontakt

(Frage: Ausgerechnet bei Köln, gibt es ein Kontaktformular, wie gehen wir damit um?)

Liste bitte als Dokument pflegen.

**Comment by ghost** [comment]
In Köln sind wir mit den Ansprechpartnern z.B. über soziale Netzwerke vernetzt

**Comment by tilladams** [comment]
Timebox max. 3h.

**Comment by tilladams** [comment]
per Twitter im Nachgang zur FOSSGIS haben uns kontaktiert:
- Open Data Sachsen
- @OpenDataKoeln 
- @OpenDataDdorf 
- @OpenNRW 
- @govdata_de 
- @milafrerichs
- @KalliPick

**Comment by GeoLotti** [comment]
[Kontakte_MetaOpenData.xlsx](https://github.com/mundialis/metaopendata/files/1942702/Kontakte_MetaOpenData.xlsx)

Hier die ersten Kontakte die ich auffinden konnte (Twitter und eigene Recherche).
Ich bin mir grundsätzlich unsicher wie das mit Datenschutz aussieht? Können wir denen das wirklich alle bedenkenlos zuschicken? Ich habe auch die Email zweier Privatpersonen oder auch von Privatpersonen aus bestimmten "OpenData-Abteilungen" gefunden - daher würde ich das vorher auch gerne geklärt wissen. Leider war es mir auch nicht immer möglich direkte Email-Adressen zu finden, häufig gab es nur Kontaktformulare oder nur die allgemeinen städtischen Kontakte, z.B.: "info@bochum.de"

**Comment by ghost** [comment]
Es macht auf jeden Fall Sinn, diese Liste nicht im GitHub zu pflegen. Ansonsten müssen wir das nochmal bilateral durchgehen

**Comment by tilladams** [comment]
TODO: @tilladams & @segoerke telefonieren zeitnah zum weiteren Vorgehen
