### ISSUE TITLE
0.2. Ergebnis Planung/Projektablauf an TÜV

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#11]
Projektträger wartet auf Projektplanung
-> Zusammenfassung aus Meeting 18.04.2018

**Comment by tilladams** [comment]
-> Zusammenfassung auch aus Meeting 14.06.

**Comment by tilladams** [comment]
- beim TÜV Nachfragen wie genau der Abschußbericht aussehen soll.

**Comment by tilladams** [comment]
Liste der Veranstaltungen wo das Projekt vorgestellt wurde

**Comment by tilladams** [comment]
Hallo @segoerke . Ich habe hierzu einen Draft unter:
https://github.com/mundialis/metaopendata/wiki/Zwischenbericht-an-Projekttr%C3%A4ger
abgelegt. Kannst du den bitte zeitnah mal durchsehen und ggf. ergänzen?

**Comment by ghost** [comment]
@tilladams ich habe den Vortrag bei unserer JobNight ergänzt und bin einmal alles durchgegangen. Aus meiner Sicht kann man diesen Zwischenbericht so herausgeben.

**Comment by tilladams** [comment]
report sent
