### ISSUE TITLE
2.1.0. Übersicht über die gängigen Metadaten-Profile

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#12]
Erstellung einer Übersicht über die gängigen Metadaten-Profile:

- INSPIRE
- ISO
- ...

**Comment by ghost** [comment]
Bei der Betrachtung sollte auf jeden Fall auch DCAT mit seinen Konrektisierungen DCAT-AP und DCAT-AP.de beachtet werden.

**Comment by tilladams** [comment]
@geofabi , @GeoLotti bitte in den von uns in AP I betrachteten Portalen (CMEMS, BSH, ...) Querschnitt gemeinsamer Metadatenfelder der untersciedlichen (INSPIRe-konformen) Profile herausarbeiten.

**Comment by ghost** [comment]
Achtung: Es gibt auch noch #8 Ist das ein Duplikat?

Hier einmal die meiner Meinung nach am sinnvollsten zu betrachtenden Metadatenprofile/ -modelle, die wir ausgeben können sollten:
- ISO 19139/19115 (insbesondere weil INSPIRE Voraussetzung, siehe Dokumente: https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139 , https://inspire.ec.europa.eu/documents/inspire-metadata-implementing-rules-technical-guidelines-based-en-iso-19115-and-en-iso-1

- DCAT-AP / DCAT-AP.de / GeoDCAT: Ist jetzt bereits de facto Standard für Open Data Metadaten. DCAT-AP ist die europäische Variante von DCAT. DCAT-AP.de eine deutsche Konkretisierung. GeoDCAT wird als Metadatenformat im OGC Umfeld diskutiert. Wird an Relevanz hinzugewinnen. Bspw. auch deshalb: https://ies-svn.jrc.ec.europa.eu/projects/metadata/wiki/Alignment_of_INSPIRE_metadata_with_DCAT-AP
https://inspire-reference.jrc.ec.europa.eu/vocabularies/tags/dcat
http://www.opengeospatial.org/blog/2630

**Comment by ghost** [comment]
Im Prinzip könnten wir die minimale Schnittmenge dieser Formate/ Profile als Mindeststandard definieren. Da kommt wahrscheinlich etwas in der Richtung heraus, die wir uns vorgestellt haben (10 Metadatenfelder, die wir betrachten)

**Comment by bildesheim** [comment]
Schließe mich Sebastians Einschätzung an, dass ISO 19139/19115 und DCAT-AP(.de) zu priorisieren zielführend wäre.

**Comment by geofabi** [comment]
Metadaten(felder), die aus meiner Sicht interessant sein könnten (Achtung, ich habe einen Fernerkundungs-"Bias"): 

1) **Titel**: Name / Bezeichnung des Datensatzes (bspw. Sentinel-2 Level 2A"
2) **Beschreibung**: Abstract, kurze Beschreibung
3) **Themenkategorie**: Keywords, bspw. "Verkehr", "Satellitenbild"
4) **Räumliche Abdeckung**: Area of Interest, Bounding Box (Koordinaten)
5) **Zeit**: Aufnahmedatum, Erstellungsdatum, letztes Aktualisierungsdatum
6) **Kontakt**: Kontaktperson -/ Organisation, Anschrift oder Adresse
7) **Räumliches Bezugssystem**: bspw. "UTM Zone 51 WGS84" 
8) **Für Rasterdaten: räumliche Auflösung:** Pixelgröße

Ich denke, aus den Daten direkt (bspw. Header von GeoTIFFS) kann man (4) und (7-8) ableiten. Darüber hinaus fände ich die i.d. Daten enthaltenen Attribute interessant, bspw. bei Satellitenbildern die Anzahl und Benennung der spektralen Kanäle (geht bei Sentineldaten aus den Dateien direkt oder eben über MD), oder in Vektordaten die enthaltenen Attributfelder.

Was denkt Ihr?

**Comment by ghost** [comment]
Halte ich grundsätzlich für sinnvoll, sollte aber noch mit den zu betrachtenden Profilen abgeglichen werden. Ferner ist die Festlegung auf die "Zielfelder" doch das Thema aus #13 ;-)

**Comment by ghost** [comment]
Sind wir denn hinsichtlich der zu betrachtenden Profile einig, dass wir ISO und DCAT-AP.de betrachten und eine Schnittmenge der Zielfelder definieren?

**Comment by tilladams** [comment]
Ich denke wir sollten die zu betrachtenden Felder auch vor dem Hintergrund der Machbarkeit anschauen. Da würde bei der auflistung oben der Pun kt 6. m.E. rausfallen. Das wird nicht automatisiert gehen. Auch 5. ist zumindest in der Auflösung schwierig und ggf. etwas zu EO-lastig (Aufnahmedatum).

**Comment by tilladams** [comment]
bitte künftige Diskussion zu konkreten Feldern in #13 führen.

**Comment by tilladams** [comment]
TODO: Gegenüberstellung der Standards, die wir betrachten wollen, Text in WIKI Struktur ablegen

DoD: Gegenüberstellung ist im WIKI abgelegt, es ist final festgelegt, wie damit im Prototypen verfahren wird.

**Comment by ghost** [comment]
Unter https://github.com/mundialis/metaopendata/wiki/Vergleich-der-Metadatenprofile-DCAT-AP.de-und-INSPIRE findet sich ein Vergleich der beiden Standards. Dieser ist dort in einer ersten Version abgelegt.

**Comment by geofabi** [comment]
Sehr geehrte Damen und Herren,
      
      vielen Dank für Ihre E-Mail.
      
      Derzeit befinde ich mich außer Haus, bin aber ab TT.MM.JJJJ wieder
      für
      Sie erreichbar. Ihre E-Mail wird während meiner Abwesenheit nicht
      weitergeleitet.
      
      Bitte wenden Sie sich in dringenden Fällen telefonisch an unsere
      Zentrale: 0228 - 962 899 - 51 / 0228 - 387 580 80 oder
      senden Sie eine E-Mail an: info@terrestris.de / info@mundialis.de
      
      Vielen Dank.
      
      Mit freundlichen Grüßen
      
      xxxxxxxx
    -- 
Dr. Fabian Löw
-Earth Observation Senior Consultant-

mundialis GmbH & Co. KG
Kölnstraße 99
53111 Bonn

Tel: +49 (0)228 / 38 75 80 -80
Fax: +49 (0)228 / 96 28 99 -57

Email: loew@mundialis.de
Web: https://www.mundialis.de

Amtsgericht Bonn, HRA 8528
Komplementärin: mundialis Verwaltungsgesellschaft mbH
vertreten durch: Dr. Markus Neteler, Hinrich Paulsen, Till Adams
  
Informationen über Ihre gespeicherten Daten finden Sie auf unserer Homepage unter folgendem Link: 
https://www.mundialis.de/datenschutzerklaerung
