### ISSUE TITLE
2.1.1. Ableitung minimales "Standard"-Profil

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#13]
aus Issue "[2.1.0. Übersicht über die gängigen Metadaten-Profile](https://github.com/mundialis/metaopendata/issues/12)" soll ein minimales für uns gültiges Profil erstellt werden, das beispielhaft Metadata-Tags enthält, die wir im Rahmen de Studie betrachten.

DoD: Das im Prototyxpen betrachtete Profil ist abgestimmt, festgelegt und dokumentiert.

**Comment by tilladams** [comment]
DoD: minimales Profil liegt vor und ist abgestimmt

**Comment by tilladams** [comment]
Vorschlag von @geofabi : 
Metadaten(felder), die aus meiner Sicht interessant sein könnten (Achtung, ich habe einen Fernerkundungs-"Bias"): 

1) **Titel**: Name / Bezeichnung des Datensatzes (bspw. Sentinel-2 Level 2A"
2) **Beschreibung**: Abstract, kurze Beschreibung
3) **Themenkategorie**: Keywords, bspw. "Verkehr", "Satellitenbild"
4) **Räumliche Abdeckung**: Area of Interest, Bounding Box (Koordinaten)
5) **Zeit**: Aufnahmedatum, Erstellungsdatum, letztes Aktualisierungsdatum
6) **Kontakt**: Kontaktperson -/ Organisation, Anschrift oder Adresse
7) **Räumliches Bezugssystem**: bspw. "UTM Zone 51 WGS84" 
8) **Für Rasterdaten: räumliche Auflösung:** Pixelgröße

Ich denke, aus den Daten direkt (bspw. Header von GeoTIFFS) kann man (4) und (7-8) ableiten. Darüber hinaus fände ich die i.d. Daten enthaltenen Attribute interessant, bspw. bei Satellitenbildern die Anzahl und Benennung der spektralen Kanäle (geht bei Sentineldaten aus den Dateien direkt oder eben über MD), oder in Vektordaten die enthaltenen Attributfelder.

**Comment by ghost** [comment]
Eine erste Version des Textbausteins inklusive Ableitung aus den beiden betrachteten Metadatenstandards DCAT-AP.de und INSPIRE findet sich unter: https://github.com/mundialis/metaopendata/wiki/Minimalprofil

**Comment by tilladams** [comment]
we close this ticket, duplicate to #14
