### ISSUE TITLE
4.0.1. Aufsetzen minimales Profil in GNOS

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#14]
Das minimale Profil aus [Ableitung minimales "Standard"-Profil](../issues/13) soll in GNOs implementiert werden.

DoD: Das Profil ist in GNOS auswählbar und Metadaten zu Datensätzen mt diesem Profil können angelegt werden. Beispieldatenstze sind angelegt.

**Comment by tilladams** [comment]
kann erst erledigt werden wenn #13 abgeschlossen ist.

**Comment by tilladams** [comment]
ich habe ein ISO-konformes Profil hochgeladen, dieses bitte dokumentieren (xls-Liste) und ggf. Felder löschen, Defaults anpassen etc. pp. Dazu Spalte "Zuweisung" hinzufügen und detektieren, welches der Felder ggf. durch Datenbetrachtung bzw. KI gefüllt werden könnte.

**Comment by GeoLotti** [comment]
Ich habe ein Dokument hochgeladen in dem erstmal nur das Profil dokumentiert wird in Excel: Tabelle_MOD_Standardprofil.ods

**Comment by GeoLotti** [comment]
Ich habe eine kleine Grafik erstellt, die erklärt, wie die einzelnen Felder des Metadatensatzes ausgefüllt werden können: https://github.com/mundialis/metaopendata/blob/master/dokumente/Metadatensatz_Erkennung.xml

**Comment by ghost** [comment]
Also meinem Verständnis nach handelt es sich bei dem Diagramm um ein mit anderer Notation ausgedrücktes Activity Diagramm wie diese bereits in der entsprechenden Datei "activity-diagramme.xml" vorhanden sind ;-)
