### ISSUE TITLE
4.0.0. Aufsetzen Test, Entwicklungs- und Showumgebung

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#15]
Aufsetzen einer Umgebung, in der der Prototyp laufen und nach außen hin demonstriert werden kann.
Beinhaltet Server, Prototyp und GNOS

DoD
GNOS ist up&Running

**Comment by tilladams** [comment]
s. auch #39

**Comment by ghost** [comment]
@tilladams Wir sollten uns noch auf einen CSW-Katalog festlegen, welchen wir harvesten wollen. Ich schlage hier den geodatenkatalog.de vor, der sollte das allermeiste aus Deutschland beinhalten.

**Comment by ghost** [comment]
Damit wir eine entsprechende Daten- und Metadatenmenge im Zugriff haben, ist es erforderlich, dass die Daten zu den Metadaten heruntergeladen werden. 
Folgendes Vorgehen wurde von @tilladams und mir dazu besprochen:
* Über das Harvesting des GNOS kommen die Metadaten ins System
* Über ein zu entwickelndes Tool werden die Metadaten hinsichtlich der Links unter TransferOptions überprüft (funktionieren die Links und handelt es sich um einen WFS Link)
* Die Daten werden mit entsprechenden GetFeature Anfragen als Dateien abgelegt.
* Die Dateien sind über ihren Namen mit einem Eintrag in der Datenbank mit den Metadaten verknüpft.

**Comment by tilladams** [comment]
Es wurde ein mundialis-internes Ticket für Jan Orzekowski erstellt: #5488

**Comment by tilladams** [comment]
Testumgebung steht soweit.

**Comment by ghost** [comment]
Bei unserem letzten Meeting kam meinerseits die Frage auf, welche Metadatensätze abgelegt werden.
Die Metadatensätze zu den WFS Schnittstellen selbst helfen uns nicht, da diese den Dienst beschreiben, nicht die Daten. Im Prinzip müsste für jeden Metadatensatz, der über die MetadataURL Elemente in der FeatureTypeList des Capabilities-Dokuments abrufbar ist, der entsprechende Datensatz gezogen werden. Wenn nur die Metadatensätze zu den Dienstschnittsellen vorhanden sind, haben wir 1-n Beziehungen zwischen Metadaten und Datensätzen.
Kann das noch einmal jemand prüfen?
