### ISSUE TITLE
2.3.1. System-Architektur

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#19]
Design der Architektur von Prototypen und möglichen ausgebauten Systems.
Für das Zeichnen wird draw.io verwendet.

Vorgehen:
Auftakt mit Architekturskizze, danach Weiterverarbeitung direkt aus Git.

DoD: 
Architekturskizze liegt als draw.io Skizze in Github abgestimmt vor.

**Comment by tilladams** [comment]
@GeoLotti : Bitte Skizze in http://draw.io erstellen gemäß [Skizze](https://github.com/mundialis/metaopendata/blob/master/dokumente/DSC_3127.JPG) 
Original liegt auf deinem Schreibtisch, bei Fragen, frag @geofabi 
Skizze bitte dann ins Github hier legen!

**Comment by tilladams** [comment]
@geofabi Parallel zur Erstellung der Architektur bitte allgemeine Beschreibung der Architektur verfassen.

**Comment by bildesheim** [comment]
Gibt es schon ein Architekturdokument (als Entwurf)? Unter "dokumente" habe ich kein entsprechendes Dokument gefunden.

**Comment by tilladams** [comment]
sollte @GeoLotti machen, es gibt eine Handskizze, die digitalisiert werden soll.

**Comment by GeoLotti** [comment]
Die Architektur befindet sich unter "dokumente" 
Name: MetaOpendata_Architecture.pdf

**Comment by bildesheim** [comment]
Das PDF habe ich gesehen. Was ich suche, ist aber nicht alleine eine Architekturskizze, sondern auch eine Beschreibung. @tilladams hatte ja eine allgemeine Beschreibung auf die Todo-Liste gesetzt (siehe oben). 

Wg. der Architekturskizze: wo ist die editierbare Version? Würde da gerne ein, zwei Sachen ergänzen / konkretisieren (als Vorschlag natürlich), wenn ich darf :-)

**Comment by bildesheim** [comment]
Hab mich übrigens noch nicht vorgestellt: OLIVER Bildesheim, Manager Public Services / Solution Architect bei Sopra Steria. Nice to meet you all :-)

**Comment by tilladams** [comment]
@GeoLotti - es sollte ja eigentlich eine draw.io Skizze geben ;-)
@bildesheim - die Beschreibung bin ich noch schuldig

**Comment by geofabi** [comment]
Hallo in die Runde, ein erster, grober Entwurf für eine allgemeine Beschreibung (ist noch im Entstehen  begriffen) kann ich morgen im Verlauf des Tages hochladen... draw.io Skizze kommt spätestens morgen, ich frage @GeoLotti  wenn Sie wieder im Büro ist.

**Comment by bildesheim** [comment]
👍

**Comment by GeoLotti** [comment]
Hallo Zusammen und hallo Oliver :) - leider ist es nicht so einfach hier etwas hochzuladen was man in draw.io editieren kann. Ich habe eine Zwischenlösung gefunden die leider mit einem riesen Link zusammenhängt. Wenn man auf den Link geht, öffnet sich meine Zeinung und die kann man dann wiederum editieren:
https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7Vxbb6M4FP410Ty1wja3PPY2F%2B2stlKk7e4jBTexSiDrOG3aX78GTAK2MwViktBMHxowYDvfd87xuZiM0M18%2FY0Gi9mfaYTjEbSi9QjdjiAENrT5R9byVrR4CBYNU0oicdO2YULesWi0ROuKRHhZu5GlaczIot4YpkmCQ1ZrCyhNX%2Bu3PaVxfdRFMMVKwyQMYrX1gURsVrT60Nu2f8dkOitHBu64uPIYhM9Tmq4SMd4Ioqf8r7g8D8q%2BxBddzoIofa00obsRuqFpyoqj%2BfoGxxm2JWzFc193XN3Mm%2BKENXlA0PISxCtczjifF3srsci%2FDc7ut0bo%2BnVGGJ4sgjC7%2BsrZ520zNo%2F5GeCHT2nCBJ0wu110jynD651TBJsvzgUKp3PM6Bu%2FpXygxErIEvAFC69bZoAr7plVWPFFWyCEYbrpegsIPxCY6PFBA8AH1fGBlgYfS4OPYwAf%2B2N8cBJdZSrJz5I04Y3XUbCc5YCBOjhLRtPnjcJBDVzZk%2FcBY5gm%2BTPQAhsQcaTo9IcQViByfoEQxXHAyEu9ex1sYoT7lPCBtwxJBLlevYdluqIhFg9VlVXqx5eZljtiAZ1ipnSUk7j51o14dVrxGsbBcknCX7G5W%2FhPlzdo1fFGskVpSpzcEfR7I87VEOfGTKBfY9D9b5WWFy6WOS9XmUZZi3VOTnmdH02zz%2FfL60t%2Bnc8nwew1pc%2F85K8FTvjHJAeiHInPsRiseE6RHG7rmE5WbtI4pVsz8UTiWGoKYjLNND%2FkAoJ5%2B3VmOQlft6%2FEhTmJomwYrR2uW%2BqKNAJjSxXUK2jVFNsagYUGTLGvMP9tRQaAvd0P9jo3oS%2Fox%2FsrHdqhdHymmMMPrZvJwwX%2F%2BCNJWaZyQ9U0ZIhtW7KoQGXb17Ht7M92uZz34RSaw6euDZulq2qJoAYg14A6ADAEgOoCZI8PCVCPYZcpgJBjH1GCeoy7zAGELp0jylC70Ku9i17B6XRddDAe6ylo66IrHdlSR%2BZcdNB3cDUI5uxSx3cB3pQ5pSNZBAwyp4uujDOH14T9k5m1S2tz%2Fq8498T5PaaETzzzzG7bhNJ8qkWoVjGzx5IA5NV9FAd0Da89aS3vUXc9RQKuQkYSEmSR8a0nHPUHSjJuTt8dNxV8OV6NAaRZCccaSZKJ6rQQqoFvlZIf%2FP%2F3gL7g5Vkxglxf8k4OyokaEd9ivOAtP3FAE5JM%2BeGPDLgFxWfGi2T0LI3PqMvWm6Cl9EWrtAQsOFcugGMdkYsGQXLX0onsVWzxOl1%2F0EWgRobf1R%2BUOwJAyvmY8wZKyioc3q3z4tTp65BXnotJlqZhH4Vyx3WFgshutOQgE%2Fqkpgxyo5ZgNkg2srsZV6g06%2FVibKhC4TYopvfGUIOMxRYh0C6p4xnCx5NSOh5Ql4S%2BUjpNqq6nBhD0%2FQMC1CD%2BPjWADpo3hWp42roSZS%2FWmjJUvqyJOhT%2FXy1FWWC45ShTpPtSshw09CRNVB81ld8DkA5%2Fky55O3bT8MEI6QZqzu1J%2F5J8%2BU27pOv2WOMi9EU7UiN4Bfn9MtBblE44VnQlL61r5tiW3T25I3OxImoX73dkblM7GFXrBk7nCkHhsx%2BNZ1%2BysF2re44rdSTrokGe1ZzAOWqoVJJBMuCdmbP6Y07NIORL4NksbKCeONMVDPraQYfU3MBwsK8mamxDiRrHkyIKGzUiozQ%2Fe5Gh5iEGSQYyxYXs6KMDKkaDlMdyFiyywzCg0VFyHsCpb8FwNQDpsoomUh5Il%2FI4OYBcCSD7gADp0gO7AHqLCdct%2BjFIj4US%2FnzsETVU5hY3YgWboTY2gJouvpZQO3qqUdrD6urKLWMNPgY2QZdDtytf7vRxUR0hOITXuvIcWBV%2B2TVtXLGU1helI3M%2Brt2p6vypaHN9eWeMWxLZmji%2FvmnUlb0vg8Q12BH9yYmz0Q4vo3XWB0FFAvrTuE6vyH4q4hRD2ZU41eKC3mjr%2FQ3YQTCH7I80pTF3SleO%2FAK6QfYMvAaLdNWR26AohGRVkb8xfccknCVkOdiiSEUKzUaAuh8h0FW9TcTI9v5Vb6hn%2B%2FrsibWlV9ddV41cPQ2vJjYMOTpntaUWezpeH75OhA5PMH0hQ35z3TcUSkpbYV3HUWjWvU8r761sQDM%2F3f6%2BTWHbtz8ihO7%2BBw%3D%3D

**Comment by tilladams** [comment]
Okay, da ist die ganze Zeichnung in der URL. Wir sollten die Zeichnung an sich in git verwalten, denn bevor Oliver was ändert, brauchen wir eine Versionierung!

**Comment by bildesheim** [comment]
Hm - vielleicht sollten wir yEd nutzen. Ich verwende die Desktop-Version, es ist aber seit kurzem auch eine Browser-Variante (yEd Live) verfügbar. Speichert (Desktop) bzw. exportiert (Browser) im SVG-Format - das lässt sich gut als "Rohdatei" versionieren. - Noch ist das Diagramm überschaubar und ich könnte die "Migration" auch gerne übernehmen.

**Comment by bildesheim** [comment]
Hier mal der Link: [yEd](https://www.yworks.com/products/yed)

**Comment by bildesheim** [comment]
Korrigiere: das native Format ist graphml - das sollten wir auch verwenden, am besten auch die Desktop-Version nutzen, dann kann man auch offline arbeiten.

**Comment by tilladams** [comment]
@bildesheim: bitte keine neuen Tools wenn es sich vermeiden lässt. draw.io hat bei uns eine hohe Verbreitung und lässt sich direkt in Git einbinden, Die originäre Zeichnungi st auch damit erstellt. Wenn dein Tool draw.io lesen kann, umso besser ;-)

**Comment by tilladams** [comment]
@GeoLotti : Habe die Beschreibung der Architekturskizze von @geofabi durchgeschaut und latent korrigiert. Dabei sind mir noch 3 Dinge, die an deR skizze agepasst werden müssen aufgefallen. Danach bitte unbedingt die Skizz in editierbarem Format (wegen mit direkt als draw.io download) ins git committen.

**Comment by GeoLotti** [comment]
Hallo, ich habe jetzt unter "Architectur 2.0" eine neue, etwas korrigierte Version hochgeladen als XML Datei die in draw.io geändert werden kann, ich hoffe das klappt jetzt :)

**Comment by tilladams** [comment]
@GeoLotti wie besprochen Skizze ändern:
- Kommunikation zwischen ActiniaGDI Harvester nur noch zu eigenem CSW
- eigener CSW wird so konfiguriert, das er x- andere Knoten (Skizze rechte Seite) harvestet
- ggf. Begriff "Harvester" ändern ?!?

**Comment by bildesheim** [comment]
Kann meine Änderungen nicht pushen. Bin wohl unterprivilegiert. Kann das mal wer ändern? Thx!

**Comment by ghost** [comment]
Aus meiner Sicht ist die Architektur hinsichtlich der Bezeichnungen noch zu OGC-lastig. Wir wollen ja durchaus aus Nicht-Geodaten betrachten. Wenn wir nicht nur CS-W "anzapfen", sondern auch CKAN-Kataloge ist das ein erster Schritt dahin. 
Der Begriff Harvester ist aus meiner Sicht korrekt. Im OGC-Sprech ist das eine im CS-W Standard beschriebene Funktion, die genau das tut, was wir hier vorhaben: Metadaten aus anderen Katalogen "ernten". Und auch im CKAN Umfeld spricht man vom "Harvesting", wenn man Metadaten aus anderen Katalogen abgreift.
Hinsichtlich der Implementierung sollten wir noch prüfen, ob GNOS bereits CKAN-Knoten "abernten" kann.

**Comment by bildesheim** [comment]
Habe die Gliederung des Architekturdokuments überarbeitet.

Frage: welche Textverarbeitung nutzt Ihr eigentlich? Ich habe jetzt Apache Open Office verwendet.

**Comment by bildesheim** [comment]
Pflichte @segoerke bei: "Harvester" ist für genau derartige Komponenten "in beiden Welten" ein feststehender, eingebürgerter Begriff.

**Comment by tilladams** [comment]
@bildesheim : beim Begriff stimme ich zu. Allerdings übernimmt im Prototyp das eigentliche Harvesten das GNOS, nicht actinia. Insofern störe ich mich am Begriff "actiniaGDI - Harvester" - das ist einfach falsch.

**Comment by tilladams** [comment]
@segoerke : Ja, aber wir haben einen Prototypen. Ich sehe nicht, das wir im Rahmen des prototypen mehrere Standards weren verarbeiten können. Die aktuell vorhandenen Komponenten können aber immerhin bereits CSW: Insofern würde ich das Thema gerne argumantatorisch breiter anlegen, beim Prototypen aber beo CSW und OGC-Standard belassen - das wird sonst zu viel

**Comment by ghost** [comment]
@tilladams das bedeutet dann aber in der Konsequenz, dass der Prototyp ausschließlich Geodaten betrachten werden wird. Wenn GNOS CKAN Kataloge anbinden kann, sollten wir das zumindest exemplarisch auch vorsehen. Der Parser muss m.M.n. ja "nur" prüfen, ob ein Metadatendokument ein bestimmtes Daten-Link Feld mit einem validen Link befüllt vorhält und ggf. diese Daten mit dem Metadatensatz ablegen. Alles weitere kann ja dann in der DL Komponente ablaufen.

**Comment by tilladams** [comment]
TODO: Übertrag des Dokumentes "@Beschreibung_Architektur_CE-1.odt" ins WIKI , dabei ggf. überarbeiten.

DoD: Die Architektur ist im WIKI dokumentiert und kann als Startpunkt für die Pmlementierung des Prototypen herhalten.

**Comment by GeoLotti** [comment]
Dokument wurde übertragen.
@tilladams: Bitte überarbeitete Architektur überprüfen (Architektur_2.0.xml) anschließend füge ich diese in das WIKI Dokument ein

**Comment by tilladams** [comment]
habe die Architektur nochmals überarbeitet - sollte m.E. jetzt so recht nahe an das kommen.
