### ISSUE TITLE
1.2. Erarbeitung Metadatenqualitätsklassen

### ISSUE THREAD

**Issue by geofabi** [mundialis/metaopendata#2]
Wie sieht konkret die Definition der Klassen aus?

**Comment by ulrikeleyn** [comment]
Ich versuche mal, meine Gedanken nach dem Durchgehen der halben Tabelle in Worte zu fassen und stelle sie zur Diskussion... :)

Klasse 0: keine Metadaten vorhanden
Klasse I: Metadaten vorhanden, aber nicht in einem Standardformat
Klasse II: Metadaten vorhanden, in einem Standardformat
Klasse IV: Metadaten im Standardformat vorhanden mit Link zu originären Daten

**Comment by ghost** [comment]
Ich sehe das sehr ähnlich. Wir sollten uns möglichst nah am weit verbreiteten 5 Star Data Model orientieren: http://5stardata.info/de/
Das passt aber bereits ganz gut.

**Comment by tilladams** [comment]
Das 5* Model zielt ja aber eher auf die Formate ab. ielleicht macht es Sinn, das Ganze in einer Matrix einzuteilen? Auf der einen Seite gemäß Ulrikes Einteilung (die passt schon recht gut, wobei wir noch definieren müssen ,was mit "Standardformat" gmeeint ist - INSPIRE?) und das gekreuzt mit dem 5* Model. 
Daraus gibt es dann zum Einen eine schicke Graphik und zum anderen eine fundierte Klassifizierung.
@Fabian: Kannst du ggf. einen Ansatz aufzeigen ,wie wir die Cop-Daten auf dieser Basis bewerten? So wie ich es verstanden habe, gibt es ja für diese Daten +/- einheitliche Metadaten, korrekt?

**Comment by tilladams** [comment]
TODO: Nutzenorientierte Klassifizierung erarbeiten (ggf. mit Berücksichtigung der Ergebnisse aus der Umfrage!)
TODO: DIskussion in einer derkommenden Telkos
TODO: Finalisierung der Klassen

Mit den Klassen soll beschrieben werden, welchen Qualitätsansprüchen Eingangsdaten für die automatisierte Zuweisung entsprechen sollen ("Shit in, shit out").
 
DoD: Nutzerorientierte Klassifizierung liegt vor, eine Beschreibung erörtert, warum wir diese Klassifizierung gewählt haben.

**Comment by tilladams** [comment]
eigentlich muß das Ticket an SPora, da Ulrike hieran gearbeitet hatte.
