### ISSUE TITLE
3.2.0. Festlegung Framework

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#22]
Festlegung auf das für den DL Ansatz zu verwendende Framework. Dazu evaluierung der möglichen Frameworks

must:
Framework muss unter einer offenen Lizenz stehen,

nice: 
Framework ist in Python implementiert oder bietet eine Pythin-Schnittstelle

**Comment by tilladams** [comment]
Für den DL Workshop aus mundialis Sicht Frameworks vorsondieren.

**Comment by geofabi** [comment]
Eine Übersicht liegt hier: https://github.com/mundialis/metaopendata/blob/master/dokumente/%C3%9Cbersicht%20Deep%20Learning%20Frameworks_v002.odt 

Nach kursorischer Durchsicht tendiere ich etwas zu PyTorch (weil Python und stark wachsende Community, gute Dokumentation im Internet, unterstützt (wie viele andere DL Frameworks allerdings auch) multi-GPU Applikationen). Daneben KERAS (weil Python, nutzt TensorFlow und Theano) und Caffee/Caffee2.

Wie seht Ihr das? Gibt es Erfahrungen? Meine Beurteilung hat einen "Fernerkundungs-Bias", ggf. gibt es speziell für MD bessere Lösungen...

**Comment by ghost** [comment]
Wiki, Wiki, Wiki ;-)
Unseren Input gibt es heute aus Frankfurt.

**Comment by geofabi** [comment]
Kann man im WIKI Tabellen erstellen (ich finde gerade keine Möglichkeit dazu)? Das würde das Übertragen der Tabelle aus der Datei ins Wiki erleichtern...
