### ISSUE TITLE
4.1.0. Komponente: ActiniaGDI - Parser

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#24]
Es soll eine allgemeine Beschreibung dr komponente Actinia GDI - Harvester erstellt werden.

DoD: EIne Komponentenbeschreoibung liegt vor EIne Komponentenbeschreibung soll die Systemarchitektur auf Komponentenebene beschreiben. Dies umfasst:
- allgemeine Komponentenbeschreibung
- Komponentenskizze (falls möglich)
- Schnittstellenbeschreibung mit Beispiel

**Comment by tilladams** [comment]
ich bin nach wie vor der Meinung, das der name falschi st. Harvesten ist der korrekte Begriff, aber das Harvesten übernimmt in unserem Prototyp GNOs, nicht actinia.

**Comment by ghost** [comment]
Dann müsste aber die Architektur entsprechend angepasst werden und GNO noch zwischen die externen Katalogdienste und den Parser gepackt werden.

**Comment by tilladams** [comment]
@GeoLotti : Da hat @segoerke recht. Kannst du die Graphik entsporechend Kommentar von @segoerke und unserem Gespräch anpassen?
