### ISSUE TITLE
4.1.2. Komponente: Deep-Learning Interpreter

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#26]
Komponentenbeschreibung des DL-Interpreters (Working Name: DeepM)

DoD: EIne Komponentenbeschreoibung liegt vor EIne Komponentenbeschreibung soll die Systemarchitektur auf Komponentenebene beschreiben. Dies umfasst:
- allgemeine Komponentenbeschreibung
- Komponentenskizze (falls möglich)
- Schnittstellenbeschreibung mit Beispiel

**Comment by tilladams** [comment]
Bitte Ticket ausformulieren und entsprechende Frameworks nennen und diskutieren.

**Comment by tilladams** [comment]
wird im DL Workshop bearbeitet.

**Comment by geofabi** [comment]
Erste Version des Überblicks zu bestehenden DL Frameworks liegt hier (wird noch aktualisiert werden):

https://github.com/mundialis/metaopendata/tree/master/dokumente/Übersicht Deep Learning Frameworks.odt

**Comment by geofabi** [comment]
Erste Version des Überblicks zu bestehenden DL Frameworks liegt hier (wird noch aktualisiert werden):

https://github.com/mundialis/metaopendata/tree/master/dokumente/**Übersicht Deep Learning Frameworks.odt**
