### ISSUE TITLE
5.0.0. finaler Bericht

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#28]
Oberticket für den finalen Bericht

**Comment by GeoLotti** [comment]
Hallo Zusammen, ich würde hier gerne alle nochmal bitten auf die Struktur vom Abschlussbericht zu schauen und diese bitte zu ergänzen (#42). Vor allem fehlen ein paar Texte und Kapitel zur DeepLeanring- Komponente bei denen ich leider nur wenig zu beitragen kann.
