### ISSUE TITLE
5.0.1. Glossar für Abschlußbericht

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#29]
Bei der Masse an Fachbegriffen, die wir zwangsläufig verwenden, benötigen wir m.E. ein Glossar. Alleine in der Beschreibung der Architekturskizze sind bereits viele Fachbegriffe, und Abkürzungen, die tlw. in Klammern zumindest aufgelöst, aber nicht erläutert werden.

TODO: Gloassar initial erstellen und als Dokument im Git hinterlegen. Bitte an @alle: Glossar bei Neueinführung eines Begriffes weiterpflegen oder kennt jemand eine intelligente Softwre, womit man sowas besser pflegen kann?

**Comment by tilladams** [comment]
es gibt nun eine WIKI Seite, die erstmal als Glossar dient, wird für den Abschlöußbericht dann exportiert. Bitte alle Begriffe dort eintragen.
@GeoLotti bitte Begriffe aus Beschreibung Architektur dort einpflegen

**Comment by GeoLotti** [comment]
Glossar und Verlinkungen mit WIKI-Seiten steht: https://github.com/mundialis/metaopendata/wiki/Abschlussbericht-Entwurf

Hier können alle parallel arbeiten und am Ende werden die Inhalte aus dem Wiki in SCs angelegtes Dokument übertragen: MOD_templ_03.odt (https://github.com/mundialis/metaopendata/blob/master/dokumente/Templates_SC/MOD_templ_03.odt)
