### ISSUE TITLE
1.1.0. Erstellung Datenübersicht

### ISSUE THREAD

**Issue by geofabi** [mundialis/metaopendata#3]
**Todo:** 
Datenformat (Datensatz, Datenservice), Datenmodell, INSPIRE-Datenmodell, Copernicus-Datenmodell, OKSTRA-Straßendatenmodell etc.; Zielmodelle Metadaten definieren,Datenmodelle für Copernicus, Kanäle, Räumliche / Zeitliche Auflösung, INSPIRE-Konformität, Satelliten- und Diensteportal / Metadatenportal der EU; Einschränkung auf Dienste des BSH; Sentinel Daten

**Ergebnis**
Liste mit Datensätzen, Vorklassifizierung

**Comment by geofabi** [comment]
Erste, nicht-systematische Übersicht zu Datenbestand BMVI mCLOUD Copernicus auf GitHub
https://github.com/mundialis/metaopendata/wiki/Datenbestand-BMVI---mCLOUD---Copernicus

**Comment by tilladams** [comment]
Zusammenfassung wird im Rahmen von #5 erlediugt, daher wird dieses Ticket geschlossen
