### ISSUE TITLE
4.1.4. Komponente Geonetwork Open Source

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#31]
Es soll eine allgemeine Beschreibung der Komponente GNOS erstellt werden.

DoD: EIne Komponentenbeschreoibung liegt vor EIne Komponentenbeschreibung soll die Systemarchitektur auf Komponentenebene beschreiben. Dies umfasst:

allgemeine Komponentenbeschreibung
Komponentenskizze (falls möglich)
Schnittstellenbeschreibung mit Beispiel

**Comment by tilladams** [comment]
Bitte eine allgemeingültige Beschreobung der Komponente GNOS in ein Doc schreiben (1/2 - 1 Seite) - es gibt viele Beschreibungen im Web.

**Comment by bildesheim** [comment]
Die Beschreibung der Komponente sollte m.E. im Architekturdokument erfolgen.
Habe hierfür in der Architekturbeschreibung unter Kap. "Softwarearchitektur" - Unterkap. "Komponentenbeschreibung" einen Abschnitt "GNOS" angelegt (siehe Beschreibung_Architektur_CE-1.odt).

**Comment by ghost** [comment]
Ich denke auch, es macht Sinn, die Komponenten im Rahmen der Architektur zu beschreiben.

**Comment by tilladams** [comment]
JO hat den Testserver eingerichtet (internes Ticket #5488 und auch das Harvesting eingerichtet (5489) . Bitte URL + Zugänge zu GNOs checken und Admin-PW auch an Sebastian Goerke senden, JO fragen, was er von SebGo braucht, um ihm SSL Zugriff gewähren zu können

**Comment by GeoLotti** [comment]
Beschreibung abrufbar unter: Beschreibung_GNOS.odt (https://github.com/mundialis/metaopendata/blob/master/dokumente/Beschreibung_GNOS.odt)
