### ISSUE TITLE
4.1.4.1. Howto Usage GNOS

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#32]
Internetrecherche Workshops/Kurzeinführung Benutzung GNOS (v 3.4.x.)
- Projekthomepage 
- OSGeo
- Geo4All
- Fa. Geocat

**Comment by GeoLotti** [comment]
Erste Hinweise:
- https://geonetwork-opensource.org/ : Erste Infos wie man Daten beschreibt und publiziert
- https://www.weichand.de/category/geonetwork/ : Schriftliche Tutorials (z.B. GeoNetwork Harvesting fernsteuern usw.)

Diese sollten eventuell einmal durchgespielt werden?

**Comment by tilladams** [comment]
internen Workshop CE, FL, TA ogrganisieren

**Comment by tilladams** [comment]
Bitte Self-Training am 20.06. durchführen

**Comment by GeoLotti** [comment]
Tutorials: Introduction to Geonetwork - https://geonetwork-opensource.org/manuals/3.4.x/ge/tutorials/introduction/index.html
