### ISSUE TITLE
2.3.1.1. UML Diagramm für Architektur erstellen

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#33]
Es soll ein UML Diagramme für die Architektur erstellt werden.

DoD: UML Diagramme sind erstellt, im Git abgelegt und eine Erläuterung im WIKI abgelegt.

**Comment by ghost** [comment]
Ich habe zwei neue Dokumente angelegt, die UML Diagramme enthalten, die mittels draw.io erstellt wurden. Diese sind erst einmal recht rudimentär gehalten und sollen das System abgrenzen und die Abläufe skizzieren.

**Comment by tilladams** [comment]
beim usecase fehlr m.E. das Einbinden anderer Kataloge, die ja per "Harvest" als Input für DL-Algorithmen dienen sollen. Generell fände ich es gut, wenn wir die Diagramme etwas "sprechender" benennen würden.

**Comment by ghost** [comment]
Das ist der Use Case "Trainingsdaten einspielen" meiner Meinung nach.
Was meinst du genau mit "sprechender"? Ein Use Case Diagramm ist ein Use Case Diagramm ;-)

**Comment by ghost** [comment]
https://github.com/mundialis/metaopendata/blob/master/dokumente/activity-diagramme.xml
https://github.com/mundialis/metaopendata/blob/master/dokumente/usecase-diagramm.xml
