### ISSUE TITLE
3.0.2. Beschreibung Umfrage

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#35]
Beschreibung über Vorgehen, Inhalt sowie Ziele unserer Umfrage. 
Dient auch #30 und #28 

Sobald eine Auswertung vorliegt, passt die hier hinein.

**Comment by geofabi** [comment]
Erledigt, ich lege es bei den Dokumenten ab: [](https://github.com/mundialis/metaopendata/tree/master/dokumente)

**Comment by geofabi** [comment]
z.K. habe die Umfrage bis Ende August verlängert
