### ISSUE TITLE
0.3. WIKI Seiten Anlegen für finalen Bericht

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#37]
Der finale Bericht soll zunächst im WIKI gepflegt werden. Dazu muß die Struktur des Berichtes im WIKI angelegt werden.

DoD: Die Projektstruktur ist im WIKI abgelegt und an Stellen, wo schon Ergebnisse vorliegen, sind diese eingeplfegt.

**Comment by GeoLotti** [comment]
Ich habe die erste Struktur (die bereits von @bildesheim angefertigt wurde) in eine Wiki-Seite übertragen. Hier ist es  vorerst einfacher, dass alle dran arbeiten können.
https://github.com/mundialis/metaopendata/wiki/Abschlussbericht-Entwurf

**Comment by bildesheim** [comment]
Wiki ist eine gute Idee. Das erleichtert die kollaborative Dokumentenerstellung / -pflege (weiter).

Soll der Abschlussbericht kein formales, separates Dokument mit entsprechend eigener Gliederung sein? Bzw. stellt sich auch die Frage, ob das Architekturdokument nicht (aus anderen Gründen) ein eigenständiges Dokument sein soll. - Wie seht Ihr das?

**Comment by ghost** [comment]
Ich habe beim Workshop letzte Woche bereits gesagt, dass wir 2 Liefergegenstände betrachten mussen.
* Der formale Abschlussbericht, der recht kurz gefasst erklärt, was wir gemacht haben und mit welchem Erfolg (Der muss 6 Monate nach Projektabschluss vorliegen)
* Die eigentliche Machbarkeitsstudie, deren Zusammensetzung und Inhalt uns selbst obliegt

Ich denke, wenn wir die Inhalte der Machbarkeitsstudie im Wiki zusammenstellen, lassen sich daraus beliebige Dokumente ableiten. Daher sollten wir alles, natürlich strukturiert, im Wiki an- und ablegen und dann entsprechend sinnvoll für die Machbarkeitsstudie zusammensetzen.
