### ISSUE TITLE
0.4 waffle.io in Betrieb nehmen

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#38]
In wallfe können versciedene Sichten auf GitHub Issues erstellt werden. Damit können wir Tickets für Bericht (aktuelle Tikets) und Entwicklertickets einfach trennen und dasselbe Repo benutzen.

DoD: Für die weitere Bearbeitung kann waffle.io für Bericht und Entwicklung benutzt werden.

**Comment by GeoLotti** [comment]
Ich befürchte um ein Projekt in waffle.io anlegen zu können, muss man der owner von einem repository sein https://waffle.io/project/create/choose-repository
Da ich keines habe müsste ich ein neues erstellen... mir ist leider nicht klar wie ich ein bereits existierendes hinzufügen kann

**Comment by tilladams** [comment]
habe das Repo in waffle.io angelegt. Bitte mal checken, ob du dich da mit deinem Github Account bei waffle.io einloggen kannst und ob du Zugriff auf das Projekt via waffle.io hast.
