### ISSUE TITLE
3.0.1.1. Vorbereitung DL Workshop

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#39]
Es soll am 02./03./04. ein Workshop mit den DL Experten der Sopra stattfinden.
Teilnehmer: FL, Sopra, ggf. TA und CE, prüfen ob AB teilnehmen soll.

Vorbereitung: Es soll eine "Spielwiese" eingerichtet werden.

JO soll dazu auf der OTC einen Entwicklungsserver aufsetzen und mit diesem Git-Repo verbinden. Dazu soll mindestens ein GNOS aufgesetzt werden. Das GNOS sollte idealerweise schon andere CSW Knoten harvesten.

DoD: Ein Entwicklungsserver ist eingerichtet und kann von allen Projektbeteiligten erreicht werden. Das Git-Repo ist verbunden.

**Comment by geofabi** [comment]
Hallo i.d. Runde, wie ist hier der Stand, findet der Workshop statt?

**Comment by ghost** [comment]
Ja, aber definitiv nicht in dieser Woche. Unsere Leute möchten anhand der aufgebauten Infrastruktur erste Tests machen, bevor sie einen Workshop für sinnvoll erachten.

**Comment by tilladams** [comment]
Hallo, 

nichtsdestotrotz sollten wir uns auf einen Termin einigen - wir müssen auch planen und würden gerne zumindest in Form von Fabian am Workshop teilnehmen. Sebastian, wenn du also kommende Woche einen Vorschlag machst - ich glaube, das m+sste wegen Fabian dann eher gegen Ende der Woche sein. 
Till 


Von: "Sebastian Goerke" <notifications@github.com> 
An: "mundialis/metaopendata" <metaopendata@noreply.github.com> 
CC: "Till Adams" <adams@terrestris.de>, "Assign" <assign@noreply.github.com> 
Gesendet: Dienstag, 3. Juli 2018 11:27:49 
Betreff: Re: [mundialis/metaopendata] 3.0.1.1. Vorbereitung DL Workshop (#39) 



Ja, aber definitiv nicht in dieser Woche. Unsere Leute möchten anhand der aufgebauten Infrastruktur erste Tests machen, bevor sie einen Workshop für sinnvoll erachten.

**Comment by geofabi** [comment]
Ich kann Do-Fr kommende Woche, übernächste Woche Mo-Mi.
