### ISSUE TITLE
1.2.1. Erstellung Fragebogen

### ISSUE THREAD

**Issue by geofabi** [mundialis/metaopendata#4]
Befragung / Experteninterviews und Online Fragebogen; Fortschreiben der Liste, Selektion und Priorisierung nach Datentypisierungsklassen

**Comment by geofabi** [comment]
Entwurf für Fragebogen erstellt und auf GitHub:
https://github.com/mundialis/metaopendata/wiki/ENTWURF-Umfrage

**Comment by geofabi** [comment]
Erster Online-Entwurf für die Umfrage erstellt unter: https://ec.europa.eu/eusurvey 
Einladung zum Testen kommt per E-Mail.

Frage: Geht das grundsätzlich i.d. richtige Richtung? Welche Fragen wollen wir darüber hinaus stellen?

**Comment by neteler** [comment]
Das Logo könnte noch eingebaut werden am Anfang der Umfrage:
https://www.bmvi.de/SharedDocs/DE/Bilder/DG/mfund-metaopendata.jpg?__blob=normal&size=810w

Und _vor_ "submit" der Hinweis, dass man die Auswertung erhält (wäre zumindest cool).
Alternativ vielleicht ein motivierender Satz, dass man zu <...hehres Ziel einfügen...> beigetragen hat.

**Comment by ulrikeleyn** [comment]
Ich finde den Entwurf gut, vor allem auch die Plattform! :)
Einige Anmerkungen hätte ich zum Text und auch allgemein. Wo sollen diese am besten hin - direkt hier?

**Comment by geofabi** [comment]
Hi, ich habe den gesamten EUSurvey auf eine neue Wiki-Seite gestellt: https://github.com/mundialis/metaopendata/wiki/Umfrage_EUSurvey 

Ich schlage vor, Änderungen dort rein zu schreiben, dann kann ich es später in den Survey einbauen.

**Comment by ulrikeleyn** [comment]
Für Änderungen im Text ist das sicher eine gute Idee... aber für Anmerkungen  zur Gesamtstruktur der Umfrage?

**Comment by geofabi** [comment]
Gerne als Kommentar unter der Seite einfügen, oder auch hier (bin aber offen für Alternativen :) https://github.com/mundialis/metaopendata/wiki/ENTWURF-Umfrage

**Comment by geofabi** [comment]
Gerne als Kommentar unter der Seite einfügen, oder auch hier (bin aber offen für Alternativen :) https://github.com/mundialis/metaopendata/wiki/ENTWURF-Umfrage

**Comment by ulrikeleyn** [comment]
Ich kann unter der Seite leider keinen Kommentar einfügen noch kann ich den Text bearbeiten.

**Comment by tilladams** [comment]
Die Umfrage zu den Metadaten sollte noch etwas mehr aus der Geodatenecke herausgenommen werden. Bei den Arbeitsforen hat sich gezeigt, dass viele Projekte nicht in dieser Domäne unterwegs sind. Von der wik-Begleitforschung kam das Angebot, die Umfrage auch über die Arbeitsforen-Koordination einzukippen und somit viele mFUND-Projekte zu erreichen.

@FAbian: Kannst du CHarlotte auch den Link auf den Fragebogen (Test) zukommen lassen?
TODO Charlotte: Fragebogen überarbeiten

**Comment by geofabi** [comment]
Überarbeiteter Entwurf für den Fragebogen heute per EU Survey intern verschickt

_@ alle: Feedback immer gerne :-)_

**Comment by ghost** [comment]
Zu Frage 2: Ich fände es interessant, bei den Behörden zu unterscheiden, ob diese im BMVI-Ressort sind oder nicht. Da kann man dann zumindest für die Behörden, die unser Projekt ja vom Grundsatz her am direktesten betrifft genauer feststellen, wie deren Sicht ist.

**Comment by ghost** [comment]
Bei Frage 3.2 würde ich Softwareentwicklung herausnehmen. Soweit ich es bisher überblicke, entwickeln ja alle mFUND Projekte grundsätzlich Software. Ich würde dafür aber dann Wetter/ Klimadaten mit aufnehmen, da der DWD einer der größten Datenlieferanten im BMVI ist. Den Auswahlpunkt Verkehr würde ich noch ausweiten auf Straßenverkehr, Bahnverkehr, Schiffsverkehr, Luftverkehr. Vielleicht ist auch ÖPNV sinnvoll, da in der mCLOUD ja viele ÖPNV Daten auffindbar sind.

**Comment by ghost** [comment]
Bei Frage 4.1 würde ich noch eine Auswahl "sehr gering" hinzufügen. Dann erhalten wir auf jeden Fall eine Tendenz der Antwortenden

**Comment by ghost** [comment]
Bei Frage 4.3 ist in der Klammer ein Leerzeichen zu viel zwischen "Daten" und "haltende", geht in einem Wort "Datenhaltende".

**Comment by ghost** [comment]
Bei 4.4 würde ich in der Klammer noch "DCAT" aufnehmen, das kennen Leute, die mit Open Data Portalen arbeiten eher, als INSPIRE.

**Comment by ghost** [comment]
Unter 4.5 sollte bei den Beispielen CKAN herausgenommen werden, da CKAN eine Technologie ist und kein Portal. GovData ist ein gutes Beispiel für ein CKAN Portal.

**Comment by ghost** [comment]
Bei 4.6 sollte der Ansprechpartner noch als Auswahl hinzukommen.

**Comment by tilladams** [comment]
@geofabi : Bitte Rückmeldung wie weit der Fragebogen im letzte Woche besprochenen Zustand ist.

Dazu folgende Fragen:
- aktuell ist eine personalisierte Einladung notwendig. Kann man das irgendwie so drehen, dass sich Leute selber registrieren können?

**Comment by geofabi** [comment]
Danke für die Rückmeldungen, der Fragebogen ist jetzt soweit überarbeitet - ich habe den Kundenservice angeschrieben bzgl. der Frage nach "personalisierte Einladung", leider geht das aus der Plattform bzw. den Optionen dort nicht hervor.

**Comment by tilladams** [comment]
@geofabi finale Anmerlungen:
3.4., 4.7. dürfen kein Pflichtfeld sein, es ist ja nur ergänzend

generell:
Machen Pflichtfelder überhaupt Sinn ODER SOLLEN WIR NICHT ALLES ALS "OPTIONAL" FREIGEBEN?

**Comment by geofabi** [comment]
Danke, geändert.... ich würde so viele Felder wie möglich "mandatory" setzen, um eine genügend hohe Anzahl valider Antworten für die Auswertung zu haben. Mein Vorschlag: Bei Mehrfachantworten "Weiß nicht" zulassen?

Bzgl. Veröffentlichung: wir können statt der E-Mail-gebundenen Einladung (mit indiv. Zugangscode) die finale Version der Umfrage für jedermann (!) hier online stellen: https://ec.europa.eu/eusurvey/home/publicsurveys (dann geht das auch ohne personalisierte Einladung...)

**Comment by ulrikeleyn** [comment]
Zwei Mal dafür! :)

**Comment by ghost** [comment]
Bin auch bei beiden Punkten dafür.
Vorteil beim zweiten Punkt: Wenn jeder den Fragebogen machen kann, können wir über die Begleitforschung einfach den Link verteilen lassen ;-)

**Comment by geofabi** [comment]
Danke für die Rückmeldung, ich melde unsere Umfrage bei EU-Survey zur Veröffentlichung an (der wird erst intern geprüft...)

**Comment by GeoLotti** [comment]
Hallo Zusammen, hier findet Ihr ein Draft vom Anschreiben zur Umfrage. Gebt ruhig kurz Rückmeldung hierzu.
@geofabi arbeitet gerade noch an einer "Datenschutzklausel" für die Email bzw. auch die Umfrage selber.
[Anschreiben_Umfrage.docx](https://github.com/mundialis/metaopendata/files/1983065/Anschreiben_Umfrage.docx)

**Comment by ulrikeleyn** [comment]
Irgendwie finde ich den akutellen Link zur Umfrage nicht (Sonja Thiele vom wik wollte ihn gern haben)... könnte ihn bitte jemand posten?
Frau Thiele möchte die Umfrage gern sehen, bevor sie über irgendwelche Verteiler läuft (jup, logisch). Außerdem sei es wohl fraglich, den gesamt-mFund-Verteiler zu nutzen, das müsste eher mit Frau Jasmin Geilenkirchen vom BMVI abgeklärt werden.

**Comment by GeoLotti** [comment]
Hallo Ulrike, hier der Link zur Umfrage für Externe:

Link: https://ec.europa.eu/eusurvey/runner/MetaOpenData
Passwort: MetaOpen2018!?Data

**Comment by geofabi** [comment]
Dieses Ticket ist abgearbeitet...
