### ISSUE TITLE
4.1.4.2. Harvesting im GNOS

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#40]
Das GNOS des Prototypen soll mindestens einen externen CSW-Knoten (präferiert Geoportal HH) harvesten.
Eine Übersichtsliste über Landes7Bundes-CSW Knoten findet sich hier:
https://wiki.gdi-de.org/pages/viewpage.action?pageId=136347672

Dieses ticket wurde auch als internes mundialis Ticket #5489 erstellt und wird von JO bearbeitet.

**Comment by tilladams** [comment]
konkret das hier:
http://www.metaver.de/csw/partner/hh?REQUEST=GetCapabilities&SERVICE=CSW&Version=2.0.2

**Comment by geofabi** [comment]
Testphase (d.h. das Harvesting) des o.g. CSW im GNOS läuft ...

**Comment by tilladams** [comment]
done
