### ISSUE TITLE
5.1.0. Finaler Bericht - Struktur im WIKI anlegen

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#42]
Struktur des finalen Berichtes wird im WIKI angelegt. Ein Anfang ist dort bereits gemacht. Erstmal der Struktur der Arbeitspakete folgen + im kapitel "Prototyp" ein Subkapitel "Softwarearchitektur" machen. Dort kann das Dokument "Architektur" von Oliver übernommen werden.

**Comment by bildesheim** [comment]
Hatte gestern die Architektur-Teile in eine eigene Wiki-Seite ausgelagert. Sollten das Architekturdokument wie kürzlich diskutiert separat halten und ggf. im Abchlussbericht verlinken.

**Comment by GeoLotti** [comment]
Hab eine erste Struktur angelegt: https://github.com/mundialis/metaopendata/wiki/Abschlussbericht-Entwurf

Bitte gerne korrigieren oder Anmerkungen hinterlassen.
Die oben erwähnten Architektur-Inhalte hab ich nur sehr grob übernommen da mir auch generell noch nicht ganz klar ist, wie detailliert dieser Bericht ausfallen soll

**Comment by GeoLotti** [comment]
Ich habe angefangen die Struktur im Wiki mit Hyperlinks zu versehen, so dass jedes Kapitel (Am Ende) eine eigene Wiki-Seite hat. Hier können ggf. schon Texte, Diagramme etc. eingefügt werden, damit diese nicht verloren gehen oder vergessen werden.

**Comment by tilladams** [comment]
habe das Ticket mal in "in progress" verschoben ;-)
