### ISSUE TITLE
4.1....Weboberfläche für Showcase

### ISSUE THREAD

**Issue by GeoLotti** [mundialis/metaopendata#45]
Bitte eine Weboberfläche für den Showcase erstellen die:

- Projekt- und Firmenlogos enthält, die Firmenlogos können hier eingesehen werden: https://mundialis.github.io/metaopendata/ 
- auf Impressum/Datenschutzerklärung hinweist - diese können ebenfalls auf der projekthomepage eingesehen werden: https://mundialis.github.io/metaopendata/ 
- auf der ein beliebiger Datensatz hochgeladen werden kann mit verschiedenen Geodateien (shape, tiff...)
--> der Server auf den der Datensatz hochgeladen werden soll wurde von JO eingerichtet: #5488 (Redmine): tomcat: https://bmvimetadaten.mundialis.de/
- die hochgeladene Datei wird auf dem Server in einem bestimmten Verzeichnis (bsp./home/temp/ o.ä.) abgelegt.

Bitte weiterführende Tickets beachten: #46, #47

Der Gesamten Vorgang kann hier eingesehen werden: 
Öffnen in http://draw.io: Showcase_Vorgang.xml 

DoD: Eine Webseite gemäß den oben definierten Anforderungen liegt vor und ist über den Testserver des Projektes (metaopendata.mundialis.de) aufrufbar.

**Comment by mmacata** [comment]
Webseite ist gebaut (https://bmvimetadaten.mundialis.de/)
und auch ein Anwendungsserver, der die Dateien entgegen nimmt (https://bmvimetadaten.mundialis.de/api). Dieser basiert auf actinia-gdi.
