### ISSUE TITLE
4.1....Automatisierte Übernahme der Daten in das Metadatentemplate

### ISSUE THREAD

**Issue by GeoLotti** [mundialis/metaopendata#46]
Die Informationen über den Datensatz sollen automatisch in einen bestehenden Metadatensatz übertragen werden.
Dies sollte durch die reine Betrachtung der Daten möglich sein (Die zusätzliche Alternative von Datenerfassung durch KI wird vom Projektpartner abgedeckt).

In #45 wird ermöglicht Geodaten in ein bestimmtes Verzeichnis hochzuladen. Dabei wird ein Metadatensatz erzeugt und der Titel angepasst. Diese hochgeladenen Geo-Daten sind zu betrachten und Informationen (Absprache CE oder TA z.B. mit ogrinfo o.ä.) daraus in den oben genannten Metadatensatz zu schreiben (s. dazu auch #47).

DoD: Ein serverseitiges Skript detektiert Informationen aus den hochgeladenen Datensätzen (z.B. BBOX, EPSGCode usw.) und schreibt diese in einen Metadatensatz. Dieser Metadatensatz wird anschließend in das Metadatenupload-Verzeichnis kopiert (s. #47).

**Comment by tilladams** [comment]
@Charlotte - bitt entsprechende Absprachen mit JO machen und ihm für dieses ticket als Ansprechpartner zur Verfügung stehen. Technisch kann ja auch CT helfen.

**Comment by tilladams** [comment]
die automatisierte Metadatenerfassung soll auf Basis von 2 komponenten erfolgen:
1. der Betrachtung der Daten selber
2. dem KI Ansatz
Für 1. brauchen wir ein Skript, das einen neu hochgeladenen Geodatensatz (für den über das Hochladen direkt ein Metadatensatz angelegt wird) mittels gdalinfo (z.B.) betrachtet, Koordinatensystem (falls vorhanden) und BoundingBox ausliest und diese informationen in das Metadatenprofil für den FDatensatz über die GNOs API einträgt.
Detals zu Aufbau der Demo bitte bei @mmacata erfragen

**Comment by ghost** [comment]
Komminaktion mit GNOS-Api; CSRF Token erzeugen und in Post/Get Requests wiederverwenden
TODO:

- mittles POST einen Metadatensatz mit Beispiel XML Datei anlegen
  - schlägt noch fehl: "MultipartException" "The current request is not a multipart request"
- Testdaten in irgend ein verwendbares Format Bringen um Records im GNOS anzulegen
- Prüfen ob schon ein Datensatz mit derselben ID vorhanden ist#
- Prüfen ob Update möglich
- Diesen dann überschreiben/updaten

**Comment by ghost** [comment]
Einfügen oder Updaten eines Datensatzes mittels CURL hat jetzt funktioniert.

als näachsten Schritt müsste aus den Testdaten die so aussehen:

`
Layer name: f7a92cf4-9b2f-4248-8adf-6e4e99fb820f
Geometry: Polygon
Feature Count: 1
Extent: (42.242187, 22.478514) - (47.375002, 27.330078)
Layer SRS WKT:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
properties: String (0.0)

`

Ein XML erzeugt werden welches z.B. so aussieht:
`<?xml version="1.0" encoding="UTF-8"?>
<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xmlns:gml="http://www.opengis.net/gml"
                 xmlns:gmx="http://www.isotc211.org/2005/gmx"
                 xmlns:gts="http://www.isotc211.org/2005/gts"
                 xmlns:gco="http://www.isotc211.org/2005/gco"
                 xmlns:gsr="http://www.isotc211.org/2005/gsr"
                 xmlns:xlink="http://www.w3.org/1999/xlink"
                 xmlns:gss="http://www.isotc211.org/2005/gss"
                 xmlns:srv="http://www.isotc211.org/2005/srv"
                 xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://www.isotc211.org/2005/gmd/gmd.xsd http://www.isotc211.org/2005/srv http://www.isotc211.org/2005/srv/srv.xsd http://www.opengis.net/gml http://www.isotc211.org/2005/gml/gml.xsd http://www.w3.org/1999/xlink http://www.isotc211.org/2005/xlink/xlinks.xsd">
  <gmd:fileIdentifier>
      <gco:CharacterString>d9db418c-bb43-40b0-ac4d-42005237e041</gco:CharacterString>
  </gmd:fileIdentifier>
  <gmd:language>
      <gco:CharacterString>eng</gco:CharacterString>
  </gmd:language>
  <gmd:hierarchyLevel>
      <gmd:MD_ScopeCode codeList="http://asdd.ga.gov.au/asdd/profileinfo/gmxCodelists.xml#MD_ScopeCode"
                        codeListValue="service"/>
  </gmd:hierarchyLevel>
  <gmd:hierarchyLevelName>
      <gco:CharacterString>service - distributed Z23950 zservice</gco:CharacterString>
  </gmd:hierarchyLevelName>
  <gmd:contact>
      <gmd:CI_ResponsibleParty>
         <gmd:organisationName>
            <gco:CharacterString>Geoffrey's Tube Australia</gco:CharacterString>
         </gmd:organisationName>
         <gmd:role>
            <gmd:CI_RoleCode codeList="http://asdd.ga.gov.au/asdd/profileinfo/gmxCodelists.xml#CI_RoleCode"
                             codeListValue="resourceProvider"/>
         </gmd:role>
      </gmd:CI_ResponsibleParty>
  </gmd:contact>
  <gmd:dateStamp>
      <gco:Date>2009-10-15</gco:Date>
  </gmd:dateStamp>
  <gmd:metadataStandardName>
      <gco:CharacterString>ISO 19115:2003/19139</gco:CharacterString>
  </gmd:metadataStandardName>
  <gmd:metadataStandardVersion>
      <gco:CharacterString>1.0</gco:CharacterString>
  </gmd:metadataStandardVersion>
  <gmd:identificationInfo>
      <srv:SV_ServiceIdentification>
         <gmd:citation>
            <gmd:CI_Citation>
               <gmd:title>
                  <gco:CharacterString>The Geoffrey's Tube Z3950 Server (Sample Record - Please Delete!)</gco:CharacterString>
               </gmd:title>
               <gmd:date>
                  <gmd:CI_Date>
                     <gmd:date>
                        <gco:Date>2010-03-24</gco:Date>
                     </gmd:date>
                     <gmd:dateType>
                        <gmd:CI_DateTypeCode codeList="http://asdd.ga.gov.au/asdd/profileinfo/gmxCodelists.xml#CI_DateTypeCode"
                                             codeListValue="revision"/>
                     </gmd:dateType>
                  </gmd:CI_Date>
               </gmd:date>
               <gmd:citedResponsibleParty>
                  <gmd:CI_ResponsibleParty>
                     <gmd:individualName>
                        <gco:CharacterString/>
                     </gmd:individualName>
                     <gmd:organisationName>
                        <gco:CharacterString>Geoffrey's Tube Craftsmen</gco:CharacterString>
                     </gmd:organisationName>
                     <gmd:contactInfo>
                        <gmd:CI_Contact>
                           <gmd:phone>
                              <gmd:CI_Telephone>
                                 <gmd:voice>
                                    <gco:CharacterString/>
                                 </gmd:voice>
                              </gmd:CI_Telephone>
                           </gmd:phone>
                           <gmd:address>
                              <gmd:CI_Address>
                                 <gmd:electronicMailAddress>
                                    <gco:CharacterString/>
                                 </gmd:electronicMailAddress>
                              </gmd:CI_Address>
                           </gmd:address>
                           <gmd:onlineResource>
                              <gmd:CI_OnlineResource>
                                 <gmd:linkage>
                                    <gmd:URL>http://www.google.com</gmd:URL>
                                 </gmd:linkage>
                                 <gmd:description>
                                    <gco:CharacterString>Home URL</gco:CharacterString>
                                 </gmd:description>
                              </gmd:CI_OnlineResource>
                           </gmd:onlineResource>
                        </gmd:CI_Contact>
                     </gmd:contactInfo>
                     <gmd:role>
                        <gmd:CI_RoleCode codeList="http://asdd.ga.gov.au/asdd/profileinfo/gmxCodelists.xml#CI_RoleCode"
                                         codeListValue="owner"/>
                     </gmd:role>
                  </gmd:CI_ResponsibleParty>
               </gmd:citedResponsibleParty>
            </gmd:CI_Citation>
         </gmd:citation>
         <gmd:abstract>
            <gco:CharacterString>This catalog is for registering all metadata records held by the Geofffrey's Tube Palace Hotel Ballroom.</gco:CharacterString>
         </gmd:abstract>
         <srv:serviceType>
            <gco:LocalName>ISO 23950 gateway</gco:LocalName>
         </srv:serviceType>
         <srv:extent>
            <gmd:EX_Extent>
               <gmd:geographicElement>
                  <gmd:EX_GeographicBoundingBox>
                     <gmd:westBoundLongitude>
                        <gco:Decimal>112</gco:Decimal>
                     </gmd:westBoundLongitude>
                     <gmd:eastBoundLongitude>
                        <gco:Decimal>154</gco:Decimal>
                     </gmd:eastBoundLongitude>
                     <gmd:southBoundLatitude>
                        <gco:Decimal>-44</gco:Decimal>
                     </gmd:southBoundLatitude>
                     <gmd:northBoundLatitude>
                        <gco:Decimal>-9</gco:Decimal>
                     </gmd:northBoundLatitude>
                  </gmd:EX_GeographicBoundingBox>
               </gmd:geographicElement>
            </gmd:EX_Extent>
         </srv:extent>
         <srv:couplingType gco:nilReason="unknown"/>
         <srv:containsOperations>
            <srv:SV_OperationMetadata>
               <srv:operationName>
                  <gco:CharacterString>ASDD nodes zserver</gco:CharacterString>
               </srv:operationName>
               <srv:DCP gco:nilReason="unknown"/>
               <srv:connectPoint>
                  <gmd:CI_OnlineResource>
                     <gmd:linkage>
                        <gmd:URL>z3950://www.google.com:6668/geonetwork</gmd:URL>
                     </gmd:linkage>
                     <gmd:protocol>
                        <gco:CharacterString>z3950</gco:CharacterString>
                     </gmd:protocol>
                     <gmd:description>
                        <gco:CharacterString>ASDD Z3950 zserver</gco:CharacterString>
                     </gmd:description>
                     <gmd:function>
                        <gmd:CI_OnLineFunctionCode codeList="http://asdd.ga.gov.au/asdd/profileinfo/gmxCodelists.xml#CI_OnLineFunctionCode"
                                                   codeListValue="search"/>
                     </gmd:function>
                  </gmd:CI_OnlineResource>
               </srv:connectPoint>
            </srv:SV_OperationMetadata>
         </srv:containsOperations>
      </srv:SV_ServiceIdentification>
  </gmd:identificationInfo>
</gmd:MD_Metadata>
`

Dieses ließe sich dann in die Datenbank eintragen.
Mir ist allerdings nicht klar welche Felder aus den Daten oben auf welche Weise und an welche Stelle in das XML-File geschrieben werden müssen

In einem ersten Test konnte ich mit dem XML Zumindest den Datensatz jedesmal überschreiben und im GNOS wurde die Änderung angezeigt.

Folgende Fragen wären für mich da noch offen:

- Anhand welcher ID kann ich Datei und Datensatz einander zuordnen?
- Nachdem der Datensatz aktualisert wurde soll dieser nochmal heruntergeladen werden und in das dateisystem geschrieben werden oder verstehe ich da was falsch.
- Das TIF-File liefert andere Rückgabe werte (json)
