### ISSUE TITLE
4.1.... Einspeisung des Metadatensatzes mit einer API (Actinia DGI) ins GNOS

### ISSUE THREAD

**Issue by GeoLotti** [mundialis/metaopendata#47]
Auf dem Server wird ein Metadatentemplate abgelegt (https://github.com/mundialis/metaopendata/blob/master/dokumente/template_metadaten_metaopendata.xml)
Ziel ist es in diesem Template den Titel zu ändern und das Template als neuen Datensatz über die GNOS API anzulegen.

Die Templates werden per suchen&ersetzen bearbeitet und dann als Datei in ein bestimmtes Zielverzeichnis abgelegt (z.B. /home/upload_metadata")
Das hochladende Skript schaut in bestimmten Zeitintervallen (z.b. alle 5 Sekunden) in dieses Verzeichnis und lädt alle darin liegenden Metadatensätze hoch und archiviert diese wiederum in ein anderes Verzeichnis (z.B. "/home/upload_metadata/archive/")).

DoD: Das oben referenzierte Template wird verwendet, der Titel ausgetauscht (gegen Dateinamen der hochgeladenen Datei) und in das entsprechende Verzeichnis kopiert. Ein neues Skript lädt aus diesem Verzeichnis alle Metadatensätze gegen die entsprechende GNOS API hoch und archiviert diese.
Im Test-GNOS ist ein neuer Metadatensatz zu sehen.

**Comment by mmacata** [comment]
After discussion:

- show clickable geonetwork Link in Client
- write filled template to FS
- submit code (without credentials ;) )
- rename back to actinia-gdi

**Comment by mmacata** [comment]
Changes to above description: actinia-gdi receives the file, replaces the name in the metadata template and creates a new metadata record immediately. It will place the filled xml template into a directory for further processing.

**Comment by mmacata** [comment]
- geodata will be uploaded to /mnt/data/metaopendata/data and templates to /mnt/data/metaopendata/templates
- template is integrated into source code. To change things, see actinia_gdi/templates/geonetwork/template_metadaten.xml
- clickable link in client inserted
- renamed to actinia-gdi
- documentation at https://bmvimetadaten.mundialis.de/api/ and swagger.json at https://bmvimetadaten.mundialis.de/api/latest/api/swagger.json
