### ISSUE TITLE
Beschreiben Prototpyen - Funktion und Architektur

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#49]
Carmen hatte ja auf Basis der Tickets #45 und #57 die Testumgebung aufgesetz. Jan ergänzt diese nochum #46 die Dateninterpreter-Komponente, dazu kommt dann noch die DL-Komponente von Sopra. 
Bitte eine Beschreibung der Testumgebung für den Abschlußbericht machen

**Comment by GeoLotti** [comment]
Beschreibung des Prototypen hier abrufbar: MOD-Showcase_Beschreibung.odt (https://github.com/mundialis/metaopendata/blob/master/dokumente/MOD-Showcase_Beschreibung.odt)
