### ISSUE TITLE
1.0. Ergebnisse AP I Zusammenfassen

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#5]
Ergebnisse aus AP I müssen verfasst werden. Hier müssen wir im Wesentlichen die Ergebnisse mCLOUD und Satellitendaten/Copernicus zusammenführen und einen Text schreiben. 

TODO SopSter: Sebastian liefert hier Ulrike hinsichtlich des mCLOUD Anteils weitere Ergebnisse zu. Ulrike verfasst zum mCLOUD Teil einen entsprechenden Ergebnistext.

TODO mund: FL liefert Charlotte Ergebnisse zu, Charlotte fasst diese zusammen.

**Comment by tilladams** [comment]
@geofabi bitte unseren Teil zusammenfassen, ggf. Kontakt zu @ulrikeleyn , ob Sie schon einen Anfang gemacht hat

**Comment by ulrikeleyn** [comment]
Hier ist mal eine Basisversion inkl. der ersten Ideen für eine Klassifizierung (3 Klassen).
[Wesentliche Erkenntnisse der mCloud.docx](https://github.com/mundialis/metaopendata/files/1949883/Wesentliche.Erkenntnisse.der.mCloud.docx)

**Comment by tilladams** [comment]
TODO sopra:
- @segoerke : Darstellung Ergebnisse zu AP I über mCLoud zusammenfassen und ins WIKI eintragen, dann Ticket an @geofabi 

TODO mund: 
- @geofabi : Darstellung Ergebnisse Copernicus danach in WIKI-Struktur einpflegen

Auswertungen und DIagramme zusätzlich ins github hochladen

DoD: Die Ergebnisse von AP I liegen im WIKI vor, Dokumente sind hochgeladen

**Comment by tilladams** [comment]
Zusätzlich: Auswertungen und Diagramme als Dokumente ins Github hochladen
