### ISSUE TITLE
Vorbereitung Zielgruppen-WS-Termin MetaOpenData

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#51]
Für einen möglichen Termin mit SH, CH (und ggf. weiteren) eine Agenda/Vorgehen erarbeiten. Termin soll in KW 39. stattfinden.

**Comment by bildesheim** [comment]
Abstimmung Agenda und Termin mit CH und SH ist angestoßen.

**Comment by akuckartz** [comment]
Ist die Stadt Köln auch beteiligt?

**Comment by bildesheim** [comment]
Zunächst Abstimmung Agenda und Termin(vorschlag) mit CH und SH. Dann wollen wir abstimmen, wen wir noch in die Runde nehmen. Köln ist schon auf unserer Wunschliste. Werde weitere Teilnehmer aber erst ansprechen, wenn wir eine grobe Agenda und einen bzw. zwei Terminvorschlag/-vorschläge vorlegen können. - Aus Eurer Sicht okay? Hatte dies so aus unserem Gespräch letzte Woche mitgenommen. Oder andere Vorschläge?
