### ISSUE TITLE
Checken wie UUID des Metadatensatzes übergeben wird

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#55]
Im Skript von CT wird nach Hochladen einer Datei automatisch ein Metadatensatz angelegt. Jeder MDS hat eine eindeutige UUID, diese wird auch für die Skripte von JO und Sopra Steria benötigt. 
Bitte herausfinden, wie diese übergeben wird.

DoD: Es ist dokumentiert, wie die UUID übergeben wird.

**Comment by ghost** [comment]
Was genau ist gemeint mit Übergeben? Von wem übergeben und an was übergeben?
