### ISSUE TITLE
0.1. Projekthomepage einrichten

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#6]
Startseite mit Infos und Kontakten zum Projekt einrichten. Diese Seite (Html) kann hier dann veröffentlicht werden (vgl. https://mundialis.github.io/fossgis2018/)

Wir brauchen:
Projektabstract
Projektpartner
Kontakt
Impressum

Wie wir das veröffentlichen ggf. mit Carmen absprechen.

Charlotte hat noch keinen Github Account, obwohl ich sie gebeten habe, sich einen anzulegen. Sie soll das hier bearbeiten.

**Comment by geofabi** [comment]
Charlotte macht einen Entwurf: https://mundialis.github.io/metaopendata/

(Impressum und Kontakt folgen noch)

**Comment by tilladams** [comment]
- Verweis auf Umfrage mit kurzer Erläuterung und Möglichkeit Emailadrese zu hinterlegen bzw. uns zu kontaktieren. TODO TA, CE mit FL klären
- Datenschutzerklärung gem. DSGVO
- SC soll Entwurf zu Homepage machen (TODO CE)

**Comment by tilladams** [comment]
@GeoLotti kannst du dich 24.04. auch darum kümmern?

**Comment by tilladams** [comment]
Datenschutzerklärungeinfügen !!!
-> z.B. https://www.terrestris.de/datenschutzerklaerung/

**Comment by tilladams** [comment]
@GeoLotti Artikel mit Erläuterung, Link und Passwort auf Umfgrage einrichten, per c&p von der moqup-Seite http://moqup.com
