### ISSUE TITLE
1.2.2. Verteilung Fragebogen

### ISSUE THREAD

**Issue by tilladams** [mundialis/metaopendata#9]
Fragebogen soll an mFUND Begleitforschung verteilt werden, daher 
- WIK, nach Supportletter fragen
- Kontakte per WIK erfragen

Kundenkontakte aller (SopSt, mund, terr) kontaktieren
- Behörden, größere Organisationen, Universitäten (?)
- Liste kontaktierter Leute austauschen

**Comment by ulrikeleyn** [comment]
Ich habe eben eine mail ans wik geschrieben. Till und Sebastian sind im CC.
